export default `

//
// This file is automatically generated.
//
// Don't edit this file, and don't put it under version control!
//

import {KatnipServer} from "katnip";

$$WORKER_DATA$$

let serverMap=new Map();

export default {
	async fetch(request, env, ctx) {
		if (env.ASSETS && env.ASSETS.fetch) {
	    	const res = await env.ASSETS.fetch(request);
	    	if (res && res.status!=404) {
	    		return res;
	    	}
		}

		if (!serverMap.get(env)) {
			let envConf={...workerData.env,...env};

			serverMap.set(env,new KatnipServer({
				modules: workerData.modules,
				importModules: workerData.importModules,
				env: envConf
			}));
		}

		let server=serverMap.get(env);
		return await server.handleRequest({request,ctx});
	}
}
`;
